#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable = /usr/bin/unbuffer

#arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/ranking/results_networktest/vgg_module.py
arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/ranking/results_networktest/mnist.3L.conv.gpu.py


var=$(network)_$(dataset)

error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
#requirements = TARGET.CUDAGlobalMemoryMb > 30000
#buffer_size = 1000
#stream_output=True
request_memory = 8040
request_cpus = 1
request_gpus = 1

network=lenet
dataset=mnist
queue 5

#
# dataset=adult
# queue 1

#dataset=intrusion
#queue 1




