#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable = /usr/bin/unbuffer

arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/ranking/results_compression/vgg_main2_tomodule.py --method $(method) --arch $(arch)


#var=lenet_$(method)_$(switch_samps)_retraining_$(dataset)_$(arch)_switch
#var=lenet_multiple_$(dataset)_$(arch)_switch

var=vgg_cifar_$(method)_$(arch)
error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
#requirements = TARGET.CUDAGlobalMemoryMb > 15000
#buffer_size = 1000
#stream_output=True
request_memory = 8040
request_cpus = 1
request_gpus = 1


#CHECK
#folder=lenet_switch_integral
#switch_point_multiple

method=switch
queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg.txt

method=l1
queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg.txt

method=l2
queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg.txt

method=fisher
queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg.txt