#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable = /usr/bin/unbuffer

arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/ranking/results_compression/lenet_network_pruning.py --arch $(arch)

#CHECK
#folder=lenet_switch
#var=lenet_integral150_retraining_$(dataset)_$(arch)_switch
var=lenet_integral1000

error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/$(folder)/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
#requirements = TARGET.CUDAGlobalMemoryMb > 30000
#buffer_size = 1000
#stream_output=True
request_memory = 8040
request_cpus = 1
request_gpus = 1

dataset=mnist

#CHECK
#queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters.txt
queue 1
arch = 5,6,40,17


#example:
#dataset=intrusion
#queue 1




