#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable = /usr/bin/unbuffer

arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/ranking/results_compression/lenet_network_pruning.py --arch $(arch) --method $(method) --switch_samps $(switch_samps) --dataset $(dataset)


var=lenet_$(method)_$(switch_samps)_retraining_$(dataset)_$(arch)_switch
#var=lenet_multiple_$(dataset)_$(arch)_switch

error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
requirements = TARGET.CUDAGlobalMemoryMb > 15000
#buffer_size = 1000
#stream_output=True
request_memory = 8040
request_cpus = 1
request_gpus = 1


#CHECK
#folder=lenet_switch_integral
#switch_point_multiple
dataset=fashionmnist
method=switch_integral
switch_samps=50

queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters.txt

dataset=fashionmnist
method=switch_integral
switch_samps=150

queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters.txt

dataset=fashionmnist
method=switch_point

queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters.txt

dataset=mnist
method=switch_point

queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters.txt



#arch = 5,6,40,17
#queue 1



#example:
#switch_samps=500
#queue 1

#switch_samps=750
#queue 1

#example:
#dataset=intrusion
#queue 1




