#executable = /home/kadamczewski/miniconda3/envs/BayesianNeuralNetwork/bin/python
executable = /usr/bin/unbuffer

arguments = /home/kadamczewski/miniconda3/bin/python /home/kadamczewski/Dropbox_from/Current_research/ranking/results_compression/vgg_main2_tomodule.py --method $(method) --arch $(arch) --switch_samps $(switch_samps) --ranks_method $(ranks_method) --switch_epochs $(switch_epochs)


#var=lenet_$(method)_$(switch_samps)_retraining_$(dataset)_$(arch)_switch
#var=lenet_multiple_$(dataset)_$(arch)_switch


error = clust/clust_err/$(var).$(Process).err
output = clust/clust_out/vgg/$(var).$(Process).out
log = clust/clust_log/$(var).$(Process).log
#requirements = TARGET.CUDAGlobalMemoryMb > 15000
#buffer_size = 1000
#stream_output=True
request_memory = 8040
request_cpus = 1
request_gpus = 1


#CHECK
#folder=lenet_switch_integral
#switch_point_multiple

switch_samps=20
ranks_method=point
switch_epochs=8

# var=vgg_cifar_$(method)_$(arch)
# method=l1
# queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg_full.txt
#
# var=vgg_cifar_$(method)_$(arch)
# method=l2
# queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg_full.txt
#
var=vgg_cifar_$(method)_$(arch)
method=fisher
queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg2.txt
#
#
# var=vgg_cifar_$(method)_$(ranks_method)_$(arch)
# method=switch
# ranks_method=point
# queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg_full.txt


var=vgg_cifar_$(method)_$(ranks_method)_$(switch_samps)_$(switch_epochs)_$(arch)
switch_epochs=8
method=switch
ranks_method=integral
switch_samps=100
queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg2.txt

# var=vgg_cifar_$(method)_$(ranks_method)_$(switch_samps)_$(arch)
# method=switch
# ranks_method=integral
# switch_samps=75
# queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg_full.txt
#
#
# var=vgg_cifar_$(method)_$(ranks_method)_$(switch_samps)_$(arch)
# method=switch
# ranks_method=integral
# switch_samps=50
# queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg_full.txt
#
#
# var=vgg_cifar_$(method)_$(ranks_method)_$(switch_samps)_$(arch)
# method=switch
# ranks_method=integral
# switch_samps=20
# queue arch from /home/kadamczewski/Dropbox_from/Current_research/ranking/utils/parameters_vgg_full.txt
#
#
#
#
